name: python CI

on:
 push:
   branches:["main"]
 pull_requeest:["main"]
   branches:["main"]
   workflow_dispatch:

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/chekout@v4
    - uses: actions/setup-python@v5
     with:
      python-version: "3.10"
    - run: |
      python -m pip install --upgrade pip
      pip innstall -r requirement.txt
    -run: pytest

